# node-graphql/docker-compose.yml

version: '3.8'
services:
  postgres:
    container_name : thread-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=thread
      - POSTGRES_PASSWORD=thread
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
